---
title: "Johan Rosa"
author: Johan Rosa
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: false
---

Aside
================================================================================

Information {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> johan.rosaperez@gmail.com
- <i class="fa fa-github"></i> [github.com/johan-rosa](https://github.com/Johan-rosa)
- <i class="fab fa-blogger"></i> [johan-rosa.com](johan-rosa.com)
- <i class="fab fa-stack-overflow"></i> [johan-rosa](https://stackoverflow.com/users/10266675/johan-rosa)


Skills {#skills}
--------------------------------------------------------------------------------

- Statistical anlysis, econometric modeling and machine learnig, web development and programming.

<<<<<<< HEAD
- Advance R, HTML, CSS, JavaScript, git, docker
=======
- Advance R, JavaScript, React
>>>>>>> b1ada38 (Update as of 2025-04-15)


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Created using [**pagedown**](https://urldefense.com/v3/__https://github.com/rstudio/pagedown__;!!MXQJGYEVCjwd!BySzNLQRtzH08e_S-q_w-vBH_9ZLVJ3OngvOwpyDrG8DtZPd_0q7wCeApEGA7XiNfCrL4w$ ).

Last update `r Sys.Date()`.



Main
================================================================================

Johan Rosa {#title}
--------------------------------------------------------------------------------

### Economist, R/Shiny developer

<<<<<<< HEAD
I'm an economist with a strong background in data analysis and R programming. My experience includes roles as an R/Shiny developer and consultant at  [Appsilon](https://appsilon.com), and as an economist with my country's central bank. I specialize in macroeconomic research, time series forecasting, data visualization, and building web applications. Committed to continuous learning and knowledge sharing, I maintain an active presence on [Stack Overflow](https://stackoverflow.com/users/10266675/johan-rosa) and regularly contribute to [my blog](https://www.johan-rosa.com/).
=======
Economist and data scientist with expertise in macroeconomic analysis, time series modeling, and web application development. Senior economist in the Central Bank of the Dominican Republic and R/Shiny consultant for multinational companies at Appsilon.
>>>>>>> b1ada38 (Update as of 2025-04-15)


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

<<<<<<< HEAD
### M.S Statistics
=======
### Master’s Degree in Research and Statistics
>>>>>>> b1ada38 (Update as of 2025-04-15)

Autonomous University of Santo Domingo

N/A

2018

### Degree in Economics

Autonomous University of Santo Domingo

N/A

2014


Laboral experience {data-icon=suitcase}
--------------------------------------------------------------------------------
### Economist

Central Bank of the Dominican Republic.

Appsilon

N/A

<<<<<<< HEAD
2022 - 2024
=======
2018 - present

::: concise
- Macroeconomic Survey Analysis. 
- Macroeconomic Indicators design.
- Economic policy evaluation.
:::


### R/Shiny developer
>>>>>>> b1ada38 (Update as of 2025-04-15)


N/A

2022 - 2024


::: concise
- Shiny developer
- Consultant
- Data Analyst
- Quality engineer
:::


<<<<<<< HEAD
### Economist

Central Bank of the Dominican Republic.

N/A

2018 - 2023

::: concise
- Macroeconomic Survey Analysis. 
- Macroeconomic Indicators design.
- Economic policy evaluation.
- Forecasting
:::

=======
>>>>>>> b1ada38 (Update as of 2025-04-15)
### Statistic Analyst

Pension Funds Superintendence

N/A

2015 - 2017

::: concise
- Research. 
- Reports and publications.
:::

Courses and certifications {data-icon=file}

### Anlayst

National Statistics Office

N/A

2012 - 2015

::: concise
- Research. 
- Poverty measurement. 
:::

Courses and certifications {data-icon=file}
--------------------------------------------------------------------------------

### JavaScript Algorithms and Data Structures

[freeCodeCamp](https://www.freecodecamp.org/certification/fcc3bb4a350-a46d-4c79-bc42-60f41ddfb9b2/javascript-algorithms-and-data-structures)

N/A

2021


### Career track: Data Anlalyst and R programmer

[Data camp](https://www.datacamp.com/profile/johanrosaperez)

N/A

2019

### Programming and data analysis with R

Autonomous University of Santo Domingo

N/A

2016

### Introduction to statistical programming with R

Autonomous University of Mexico

N/A

2016

### Multivariated analysis with applications

Autonomous University of Santo Domingo

N/A

2013


